<a href="https://colab.research.google.com/github/kuheli31/Deep-Learning/blob/main/Tensorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# In this notebook , we're going to cover some of the most fundamental concepts of the tensors using TensorFlow.

### We're going to cover:

* Introduction to Tensors
* Getting information from tensors.
* Manipulating tensors.
* Tensors & NumPy
* Using @tf.function() (a way to speed up your regular Python functions)
* Using GPUs with Tensorflow (or TPUs)

## Introduction to Tensors

In [1]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.18.0


In [2]:
# Create tensors
scalar = tf.constant(7)
vector = tf.constant([7, 8, 9])
matrix = tf.constant([[1, 2], [3, 4]])

# Format the table using raw string
table = f"""
╒══════════════╤════════════╤════════╤══════════════════════════╕
│ Tensor Type  │ Value      │ Shape  │ Rank (No. of dimensions) │
╞══════════════╪════════════╪════════╪══════════════════════════╡
│ Scalar       │ {str(scalar.numpy()):<10} │ {str(scalar.shape):<6} │ {tf.rank(scalar).numpy():<24} │
│ Vector       │ {str(vector.numpy().tolist()):<10} │ {str(vector.shape):<6} │ {tf.rank(vector).numpy():<24} │
│ Matrix       │ {str(matrix.numpy().tolist()[0]):<10} │ {str(matrix.shape):<6} │ {tf.rank(matrix).numpy():<24} │
│              │ {str(matrix.numpy().tolist()[1]):<10} │        │                          │
╘══════════════╧════════════╧════════╧══════════════════════════╛
"""

print(table)



╒══════════════╤════════════╤════════╤══════════════════════════╕
│ Tensor Type  │ Value      │ Shape  │ Rank (No. of dimensions) │
╞══════════════╪════════════╪════════╪══════════════════════════╡
│ Scalar       │ 7          │ ()     │ 0                        │
│ Vector       │ [7, 8, 9]  │ (3,)   │ 1                        │
│ Matrix       │ [1, 2]     │ (2, 2) │ 2                        │
│              │ [3, 4]     │        │                          │
╘══════════════╧════════════╧════════╧══════════════════════════╛



In [3]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [5]:
# Create a Vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Check the dimension of our vector
vector.ndim

1

In [7]:
# Create a matrix which has more than 1-Dimension.
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
# Create another matrix
another_matrix = tf.constant([[10., 7.], [3., 2.], [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
#Creating a Tensor
tensor = tf.constant([[[1 , 2 , 3] , [4 , 5 , 6]],
                      [[7 , 8 , 9] , [10 , 11 , 12]],
                      [[13 ,14 , 15] , [16 , 17 , 18]]
                     ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

### What we've created so far?

* **Scalar**: a single number
* **Vector**: a number with direction(eg. wind speed and direction)
* **Matrix**: a 2-dimensional array of numbers
* **Tensor**: an n-dimensional array of numbers(when n can be any number , a 0-dimensional tensor is a scalar , a 1-dimensional tensor is a vector)


### Creating tensors with `tf.Variable()`




In [13]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [14]:
#Create the same tensors with tf.Variable as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
#Let's try to change one of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor


TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
#How about we try .assign()?
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# Let's try to change the elements in our unchangeable tensor.
unchangeable_tensor[0] = 8
unchangeable_tensor

In [ ]:
#How about we try .assign()?
unchangeable_tensor[0].assign(8)
unchangeable_tensor

**Note:** Rarely in practice you will need to decide whether to use tf.constant or tf.Variable to create tensors , as tensorflow does this for you .However, in doubt use tf.constant and change it later if needed

# Creating Random tensors

Random tensors are tensors of some arbitrary size which contain random numbers.

In [16]:
#Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) #Setting seed
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

#Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the orders of element in a Tensor

In [25]:
#Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't affect learning)
not_shuffled = tf.constant([[10, 7], [3, 4], [2, 5]])

#Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [23]:
not_shuffled.ndim

2

In [39]:
#Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled , tf.random.set_seed(42))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [35]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

#### It looks like if we want our shuffled tensors to be in the same order , we've got to use the global level random seed as well as the operational level random seed:

> If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [40]:
tf.random.set_seed(42) #Global level random seed
tf.random.shuffle(not_shuffled , tf.random.set_seed(42)) #Operational level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

### Other ways to make tensors

In [42]:
#Create a tensor of all ones
tf.ones([3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [43]:
#Create a tensor of all zeros
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

# Turn NumPy arrays into tensors:

The main difference between NumPy arrays and Tensorflow tensors is that tensors can be run on a GPU (much faster for numerical computing).

In [44]:
#You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) #create a NumPy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) #Capital for matrix or tensor
# y = tf.constant(vector) #non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [45]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [47]:
A.ndim , B.ndim

(3, 1)

### Getting information from tensors