<a href="https://colab.research.google.com/github/kuheli31/Deep-Learning/blob/main/Tensorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# In this notebook , we're going to cover some of the most fundamental concepts of the tensors using TensorFlow.

### We're going to cover:

* Introduction to Tensors
* Getting information from tensors.
* Manipulating tensors.
* Tensors & NumPy
* Using @tf.function() (a way to speed up your regular Python functions)
* Using GPUs with Tensorflow (or TPUs)

## Introduction to Tensors

In [7]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.18.0


In [14]:
# Create tensors
scalar = tf.constant(7)
vector = tf.constant([7, 8, 9])
matrix = tf.constant([[1, 2], [3, 4]])

# Format the table using raw string
table = f"""
╒══════════════╤════════════╤════════╤══════════════════════════╕
│ Tensor Type  │ Value      │ Shape  │ Rank (No. of dimensions) │
╞══════════════╪════════════╪════════╪══════════════════════════╡
│ Scalar       │ {str(scalar.numpy()):<10} │ {str(scalar.shape):<6} │ {tf.rank(scalar).numpy():<24} │
│ Vector       │ {str(vector.numpy().tolist()):<10} │ {str(vector.shape):<6} │ {tf.rank(vector).numpy():<24} │
│ Matrix       │ {str(matrix.numpy().tolist()[0]):<10} │ {str(matrix.shape):<6} │ {tf.rank(matrix).numpy():<24} │
│              │ {str(matrix.numpy().tolist()[1]):<10} │        │                          │
╘══════════════╧════════════╧════════╧══════════════════════════╛
"""

print(table)



╒══════════════╤════════════╤════════╤══════════════════════════╕
│ Tensor Type  │ Value      │ Shape  │ Rank (No. of dimensions) │
╞══════════════╪════════════╪════════╪══════════════════════════╡
│ Scalar       │ 7          │ ()     │ 0                        │
│ Vector       │ [7, 8, 9]  │ (3,)   │ 1                        │
│ Matrix       │ [1, 2]     │ (2, 2) │ 2                        │
│              │ [3, 4]     │        │                          │
╘══════════════╧════════════╧════════╧══════════════════════════╛



In [8]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [9]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [10]:
# Create a Vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [11]:
# Check the dimension of our vector
vector.ndim

1

In [19]:
# Create a matrix which has more than 1-Dimension.
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [16]:
matrix.ndim

2

In [24]:
# Create another matrix
another_matrix = tf.constant([[10., 7.], [3., 2.], [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [25]:
another_matrix.ndim

2

In [26]:
#Creating a Tensor
tensor = tf.constant([[[1 , 2 , 3] , [4 , 5 , 6]],
                      [[7 , 8 , 9] , [10 , 11 , 12]],
                      [[13 ,14 , 15] , [16 , 17 , 18]]
                     ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [27]:
tensor.ndim

3

### What we've created so far?

* **Scalar**: a single number
* **Vector**: a number with direction(eg. wind speed and direction)
* **Matrix**: a 2-dimensional array of numbers
* **Tensor**: an n-dimensional array of numbers(when n can be any number , a 0-dimensional tensor is a scalar , a 1-dimensional tensor is a vector)
